[phases.setup]
nixPkgs = ["...", "nodejs_22", "npm-9_x"]

[phases.build]
cmds = ["npm install", "npx prisma generate", "npm run build"]

[phases.deploy]
cmds = ["npx prisma db push --accept-data-loss", "npm run start"]

[start]
cmd = "npm run start"
